### ISSUE TITLE
Error during install: No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by swasher** [noragami/igdbapi#1]
Trying `pip install igdb` on newly created virtualenv under ubuntu:

    vagrant@privategames:~$ python3 -m venv venv

    vagrant@privategames:~$ source venv/bin/activate
    (venv) vagrant@privategames:~$ python -V
    Python 3.5.2+

    (venv) vagrant@privategames:~$ pip install -U pip
    Collecting pip
      Using cached pip-9.0.1-py2.py3-none-any.whl
    Installing collected packages: pip
      Found existing installation: pip 8.1.2
        Uninstalling pip-8.1.2:
          Successfully uninstalled pip-8.1.2
    Successfully installed pip-9.0.1

    (venv) vagrant@privategames:~$ pip install igdbapi
    Collecting igdbapi
      Using cached igdbapi-0.1.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-build-mgo_m9xo/igdbapi/setup.py", line 26, in <module>
            install_requires=local_requirements(),
          File "/tmp/pip-build-mgo_m9xo/igdbapi/setup.py", line 9, in local_requirements
            with open('requirements.txt') as requirements_file:
        FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-mgo_m9xo/igdbapi/

When push to heroku, got same error. Please update pypi package.

**Comment by noragami** [comment]
Should be resolved. Thanks!
